#!/bin/bash

# if [[ $# -ne 1 ]]; then
#     echo "Usage: git init-crypto <directory>"
#     exit 1
# fi

if [[ $# -ne 2 ]]; then
echo -n Password:
read -s PASS
printf '\n'
fi

if [[ $# -eq 2 ]]; then
PASS=$2
fi

FOLDER=$1
GIT_CONFIG=".git/config"
GIT_ATTRIBUTES=".gitattributes"
CRYPTO_DIR=".git/.crypto"
CLEAN_FILTER="$CRYPTO_DIR/cleanFilter"
SMUDGE_FILTER="$CRYPTO_DIR/smudgeFilter"
DIFF_FILTER="$CRYPTO_DIR/diffFilter"

if [ ! -d "$FOLDER" ]; then
    echo "Directory does not exist: creating"
    mkdir $FOLDER
fi

git init $FOLDER
cd $FOLDER

if [ -n "$NO_CREATE_GITATTRIBUTES" ]; then
    echo "Skipping creation of .gitattributes file"
else
    echo "*.cpp filter=aes diff=aes" >> $GIT_ATTRIBUTES
    echo "*.hpp filter=aes diff=aes" >> $GIT_ATTRIBUTES
fi
########################################################
echo '[filter "aes"]' >> $GIT_CONFIG
echo "    smudge = $SMUDGE_FILTER" >> $GIT_CONFIG
echo "    clean = $CLEAN_FILTER" >> $GIT_CONFIG
echo '[diff "aes"]' >> $GIT_CONFIG
echo "    textconv = $DIFF_FILTER" >> $GIT_CONFIG
echo "" >> $GIT_CONFIG
########################################################
mkdir $CRYPTO_DIR
########################################################
echo "#!/bin/bash" >> $CLEAN_FILTER
echo "" >> $CLEAN_FILTER
echo "SALT=7F23" >> $CLEAN_FILTER
echo "" >> $CLEAN_FILTER
echo "PASS=$PASS" >> $CLEAN_FILTER
echo "" >> $CLEAN_FILTER
echo 'openssl enc -e -base64 -aes-128-cfb -S $SALT -k $PASS' >> $CLEAN_FILTER
echo "" >> $CLEAN_FILTER
chmod +x $CLEAN_FILTER
########################################################
echo "#!/bin/bash" >> $SMUDGE_FILTER
echo "" >> $SMUDGE_FILTER
echo "PASS=$PASS" >> $SMUDGE_FILTER
echo "" >> $SMUDGE_FILTER
echo 'openssl enc -d -base64 -aes-128-cfb -k $PASS' >> $SMUDGE_FILTER
echo "" >> $SMUDGE_FILTER
chmod +x $SMUDGE_FILTER
########################################################'
echo "#!/bin/bash" >> $DIFF_FILTER
echo "" >> $DIFF_FILTER
echo "PASS=$PASS" >> $DIFF_FILTER
echo "" >> $DIFF_FILTER
echo 'openssl enc -d -base64 -aes-128-cfb -k $PASS -in "$1" || cat "$1"' >> $DIFF_FILTER
echo "" >> $DIFF_FILTER
chmod +x $DIFF_FILTER
########################################################
