#!/bin/bash

if [[ $# -ne 2 ]]; then
	echo "Usage: git clone-crypto <repo URL> <directory>"
	exit 1
fi

if [ ! -d "$2" ]; then
	echo "Specified directory does not exist, creating."
	mkdir $2
fi

echo -n Enter password: 
read -s PASS
printf '\n'

echo -n Retype password: 
read -s RETYPED_PASS
printf '\n'

if [ "$PASS" != "$RETYPED_PASS" ]; then
    echo "Passwords does not match!"
    exit -1
fi

REPO=$1
DIRECTORY=$2

NO_CREATE_GITATTRIBUTES="true" git init-crypto $DIRECTORY $PASS
cd $DIRECTORY
git remote add origin "$REPO.git" -f
git config branch.master.remote origin
git config branch.master.merge refs/heads/master
git pull
