#!/bin/bash

if [[ $# -ne 3 ]]; then
	echo "Usage: git clone-crypto <repo URL> <directory> <passcode>"
	exit 1
fi

REPO=$1
DIRECTORY=$2
PASS=$3

git init-crypto $DIRECTORY $PASS
cd $DIRECTORY
git remote add origin "$REPO.git" -f
git config branch.master.remote origin
git config branch.master.merge refs/heads/master
git pull
